[package]
name = "aarch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
defmt = "^0.3.2"
crc32fast = { version = "1.3.2", default-features = false }
twpb = { path = "/home/jura/git/twpb/twpb" }